# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: asdf-micronaut ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Plugin test
      run: |
        git clone https://github.com/asdf-vm/asdf.git
        . asdf/asdf.sh
        asdf plugin-test groovy https://github.com/weibemoura/asdf-micronaut.git
  
  test_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Plugin test
      run: |
        git clone https://github.com/asdf-vm/asdf.git
        . asdf/asdf.sh
        asdf plugin-test groovy https://github.com/weibemoura/asdf-micronaut.git
